[build]
  command = "yarn run build && yarn run copy-redirects"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  from = "/authenticate"
  to = "/server/index.js"
  status = 200
  force = true

